#!/bin/bash

cache=~/.cache/wm

convert_lock="-gaussian-blur 8x4"
convert_wall="-gaussian-blur 2x1"

fifo=~/.wm/fifo

resolution=1920x1080

cache()
{
    base=`basename $1`
    name=$cache/$resolution/$3/${base%.*}.png

    if [ ! -f $name ]
    then
        mkdir -p $cache/$resolution/$3
        convert $1 -resize $resolution\! $2 $3 $name
    fi

    echo $name
}

lock()
{
    i3lock -p default -i `cache $1 $convert_lock`
}

notify()
{
    inotifywait -m -q -e move -e create -e delete --format notify ~/.wm/background
}

notify-tee()
{
    notify > $fifo
}

wall()
{
    feh --no-fehbg --bg-scale `cache $1 $convert_wall`
}

main()
{
    i=0
    xs=(~/.wm/background/*)
    nx=${#xs[@]}

    wall ${xs[0]}

    while read cmd
    do
        case $cmd
        in
            [+-]1 )
                i=$((($i%$nx$cmd%$nx)%$nx))
                wall ${xs[$i]}
            ;;

            lock )
                lock ${xs[$i]}
            ;;

            notify )
                xs=(~/.wm/background/*)
                nx=${#xs[@]}
            ;;
        esac
    done
}

main-tee()
{
    main > $fifo
}

mkfifo $fifo
trap "rm $fifo" EXIT TERM

tee >(main-tee) >(notify-tee) < $fifo > /dev/null
